### ISSUE TITLE
Demos don't work when running locally

### ISSUE THREAD

**Issue by tomscholz** [FrontendMatter/material-design-kit#1]
Hi,
I just tried to run the demos locally on my machine since the official website of yours seems to be no longer available. Unfortunately do none of the javascript powered components work. Instead I get `Uncaught TypeError: Cannot read property 'open' of undefined
    at HTMLAnchorElement.<anonymous> (reveal.html:184)`

**Comment by lazabogdan** [comment]
@tomscholz demos fixed now .. see http://mdk.frontendmatter.com
